# fonts             
$psISE.Options.FontName = 'Consolas'             
$psISE.Options.FontSize = 16             
# output pane             
$psISE.Options.OutputPaneBackgroundColor = '#FFFFEFD5'             
$psISE.Options.OutputPaneTextBackgroundColor = '#FFFFEFD5'             
$psISE.Options.OutputPaneForegroundColor = '#FF000000'             
# command pane             
$psISE.Options.CommandPaneBackgroundColor = '#FFFAEBD7'             
# script pane             
$psISE.Options.ScriptPaneBackgroundColor = '#FFFAEBD7'             
# tokens             
$psISE.Options.TokenColors.item('Command') = '#FFA0522D'             
$psISE.Options.TokenColors.item('Operator') = '#FFA0522D'             
$psISE.Options.TokenColors.item('Unknown') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('Member') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('Position') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('GroupEnd') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('GroupStart') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('LineContinuation') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('NewLine') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('StatementSeparator') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('Comment') = '#FFAEAEAE'             
$psISE.Options.TokenColors.item('String') = '#A2BC13'             
$psISE.Options.TokenColors.item('Keyword') = '#FFFFDE00'             
$psISE.Options.TokenColors.item('Attribute') = '#FF84A7C1'             
$psISE.Options.TokenColors.item('Type') = '#FF84A7C1'             
$psISE.Options.TokenColors.item('Variable') = '#EE9A00'             
$psISE.Options.TokenColors.item('CommandParameter') = '#FFFFDE00'             
$psISE.Options.TokenColors.item('CommandArgument') = '#FFFFFFFF'             
$psISE.Options.TokenColors.item('Number') = '#FF4169E1'             
$psISE.Options.TokenColors.item('LoopLabel') = '#FF4169E1'